### ISSUE TITLE
wildcard root routes not working as expected

### ISSUE THREAD

**Issue by SuddenGunter** [makasim/httprouter#4]
See [test cases](https://github.com/makasim/httprouter/compare/main...SuddenGunter:httprouter:wildcard-route?expand=1#diff-8fb3dedd34898cac9b7e2868fe6b860d3f20b458384ab1c7aaaff034852fb1a5R153-R154) added here.

Routes like `/api/{*path}` work as expected, and match long urls, like for example `/api/param/should/be/matched/by/wildcard`.

But, if I were to configure one handler to catch everything `/{*path}` - it breaks router completely. 

Is this a bug or a feature? Should I not configure routes like this?

**Comment by makasim** [comment]
Please open PR, it would be much easier to discuss the issue.

**Comment by SuddenGunter** [comment]
fixed in https://github.com/makasim/httprouter/pull/5
